language: python
matrix:
  fast_finish: true
  allow_failures:
    - env: TOXENV=py35-djmaster
    - env: TOXENV=py36-djmaster
  include:
    - python: 2.7
      env: TOXENV=py27-dj18

    - python: 2.7
      env: TOXENV=py27-dj19

    - python: 2.7
      env: TOXENV=py27-dj110

    - python: 2.7
      env: TOXENV=py27-dj111

    - python: 3.4
      env: TOXENV=py34-dj18

    - python: 3.4
      env: TOXENV=py34-dj19

    - python: 3.4
      env: TOXENV=py34-dj110

    - python: 3.4
      env: TOXENV=py34-dj111

    - python: 3.5
      env: TOXENV=py35-dj18

    - python: 3.5
      env: TOXENV=py35-dj19

    - python: 3.5
      env: TOXENV=py35-dj110

    - python: 3.5
      env: TOXENV=py35-dj111

    - python: 3.5
      env: TOXENV=py35-dj22

    - python: 3.6
      env: TOXENV=py36-dj111

    - python: 3.6
      env: TOXENV=py36-dj22

    - python: 3.6
      env: TOXENV=py36-djmaster

install:
  - pip install tox

script:
  - tox -e $TOXENV
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
before_script:
  - psql -c 'create database postgrespool_test;' -U postgres
